### ISSUE TITLE
Can not Login

### ISSUE THREAD

**Issue by antio** [pratiksh404/doctype_admin#2]
Hi, 
I tried used your template. After all step include db seed, but I can not login after that. using username n password that you gave still no luck.

Where I can check this problem?
thank you

**Comment by pratiksh404** [comment]
The problem was the seeded password value which is already hashed is rehashed by default auth controller that made password not to be matched..
Solution
try updating the package i have fixed the issue

**Comment by pratiksh404** [comment]
> Hi,
> I tried used your template. After all step include db seed, but I can not login after that. using username n password that you gave still no luck.
> 
> Where I can check this problem?
> thank you

The problem was the seeded password value which is already hashed is rehashed by default auth controller that made password not to be matched..
Solution
try updating the package i have fixed the issue

**Comment by antio** [comment]
Ah ok, thank you. 
Now when seed the db the log are changing also, why you need to change the seed step (not only user)  ? you only need to change the user seed isnt?
