### ISSUE TITLE
i am getting this error when i try to visit /admin/dashboard route

### ISSUE THREAD

**Issue by nova73-alt** [pratiksh404/doctype_admin#3]
Call to undefined method JeroenNoten\LaravelAdminLte\AdminLte::getBodyClasses() (View: C:\Users\User\Desktop\doctype_admin\resources\views\vendor\adminlte\page.blade.php)

**Comment by pratiksh404** [comment]
what about other routes... did you change anything.. or it just showed error right after installation

**Comment by pratiksh404** [comment]
> Call to undefined method JeroenNoten\LaravelAdminLte\AdminLte::getBodyClasses() (View: C:\Users\User\Desktop\doctype_admin\resources\views\vendor\adminlte\page.blade.php)

what about other routes... did you change anything.. or it just showed error right after installation

**Comment by nova73-alt** [comment]
id did 

> > Call to undefined method JeroenNoten\LaravelAdminLte\AdminLte::getBodyClasses() (View: C:\Users\User\Desktop\doctype_admin\resources\views\vendor\adminlte\page.blade.php)
> 
> what about other routes... did you change anything.. or it just showed error right after installation

id did not change anything, it is soon after installatiion

**Comment by pratiksh404** [comment]
> id did
> 
> > > Call to undefined method JeroenNoten\LaravelAdminLte\AdminLte::getBodyClasses() (View: C:\Users\User\Desktop\doctype_admin\resources\views\vendor\adminlte\page.blade.php)
> > 
> > 
> > what about other routes... did you change anything.. or it just showed error right after installation
> 
> id did not change anything, it is soon after installatiion

i think you haven't install the project's dependencies .... try 
`composer install`
