### ISSUE TITLE
if i megrate db i get this

### ISSUE THREAD

**Issue by visionto** [pratiksh404/doctype_admin#4]
hi,
if i megrate db i get this 👍 

 C:\wamp64\www\laravel7\cms\vendor\laravel\framework\src\Illuminate\Database\Connection.php:464
      PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")

  2   C:\wamp64\www\laravel7\cms\vendor\laravel\framework\src\Illuminate\Database\Connection.php:464
      PDOStatement::execute()

**Comment by pratiksh404** [comment]
> SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

check out [https://laravel-news.com/laravel-5-4-key-too-long-error](url)
**or**

- Go to config/database.php
-on connection array go to mysql array and change charset and collection from  utf8mb4 and utf8mb4_unicode_ci to utf8 and utf8_unicode_ci

**Comment by visionto** [comment]
Thanks
